# Generated by Django 3.2.9 on 2022-02-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20220105_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='langs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='язык'),
        ),
    ]
